DROP TABLE IF EXISTS test_1;
CREATE TABLE test_1 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_2;
CREATE TABLE test_2 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_3;
CREATE TABLE test_3 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_4;
CREATE TABLE test_4 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_5;
CREATE TABLE test_5 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_6;
CREATE TABLE test_6 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_7;
CREATE TABLE test_7 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_8;
CREATE TABLE test_8 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_9;
CREATE TABLE test_9 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_10;
CREATE TABLE test_10 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_11;
CREATE TABLE test_11 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_12;
CREATE TABLE test_12 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_13;
CREATE TABLE test_13 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_14;
CREATE TABLE test_14 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_15;
CREATE TABLE test_15 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_16;
CREATE TABLE test_16 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_17;
CREATE TABLE test_17 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_18;
CREATE TABLE test_18 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_19;
CREATE TABLE test_19 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

DROP TABLE IF EXISTS test_20;
CREATE TABLE test_20 (
    col1 INT NOT NULL,
    col2 INT NOT NULL,
    col3 VARCHAR(20) NOT NULL,
    col4 VARCHAR(20) NOT NULL,
    col5 VARCHAR(20) NOT NULL,
    PRIMARY KEY (col1)
);

